package com.bemtevi.bem_te_vi_api.utils;

import com.bemtevi.bem_te_vi_api.dto.ClothingDTO;
import com.bemtevi.bem_te_vi_api.dto.ClothingRequest;
import com.bemtevi.bem_te_vi_api.model.Clothing;

import java.util.Base64;

public class ClothingMapper {

    /**
     * Converts a Clothing entity to a ClothingDTO.
     *
     * @param clothing the Clothing entity
     * @return a ClothingDTO with the entity data
     */
    public static ClothingDTO toDTO(Clothing clothing) {
        return new ClothingDTO(
                clothing.getId(),
                clothing.getName(),
                clothing.getType(),
                clothing.getUserId(),
                Base64.getEncoder().encodeToString(clothing.getImageBase64()) // Convert image to Base64
        );
    }

    /**
     * Converts a ClothingRequest to a Clothing entity.
     *
     * @param clothingRequest the incoming request object
     * @param imageBytes the decoded image bytes
     * @return a Clothing entity ready for persistence
     */
    public static Clothing toEntity(ClothingRequest clothingRequest, byte[] imageBytes) {
        return new Clothing(
                null, // ID will be generated by MongoDB
                clothingRequest.getName(),
                clothingRequest.getTag(),
                clothingRequest.getUserId(),
                imageBytes // Store the raw image bytes
        );
    }
}

