package com.bemtevi.bem_te_vi_api.utils;

import com.bemtevi.bem_te_vi_api.dto.ClothingDTO;
import com.bemtevi.bem_te_vi_api.dto.OutfitDTO;
import com.bemtevi.bem_te_vi_api.dto.OutfitRequest;
import com.bemtevi.bem_te_vi_api.model.Outfit;

public class OutfitMapper {

    /**
     * Converts an Outfit entity to an OutfitDTO.
     *
     * @param outfit the Outfit entity
     * @param top the ClothingDTO representing the top clothing item
     * @param bottom the ClothingDTO representing the bottom clothing item
     * @return an OutfitDTO with the entity data
     */
    public static OutfitDTO toDTO(Outfit outfit, ClothingDTO top, ClothingDTO bottom) {
        return new OutfitDTO(
                outfit.getId(),
                outfit.getName(),
                top,
                bottom,
                outfit.getUserId()
        );
    }

    /**
     * Converts an OutfitRequest to an Outfit entity.
     *
     * @param outfitRequest the incoming request object
     * @return an Outfit entity ready for persistence
     */
    public static Outfit toEntity(OutfitRequest outfitRequest) {
        return new Outfit(
                null, // ID will be generated by MongoDB
                outfitRequest.getName(),
                outfitRequest.getTopId(),
                outfitRequest.getBottomId(),
                outfitRequest.getUserId()
        );
    }
}

