<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ad806189-267a-42dc-98ca-b8bfd08d3298</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="MongoDB.Driver" Version="2.28.0" />
    <PackageReference Include="MongoDB.EntityFrameworkCore" Version="8.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="..\.dockerignore" Link="Infra\.dockerignore" />
  </ItemGroup>

</Project>
