spring.application.name=bem-te-vi-api
spring.data.mongodb.uri=mongodb+srv://Developer:BRzVKvath81vuNrG@onca0.lx5vw.mongodb.net/bem_te_vi?retryWrites=true&w=majority
accessTokenSecret=12345
refreshTokenSecret=12345
refreshTokenExpirationDays=1
accessTokenExpirationMinutes=60